export const GET_ACCOUNT_LIST = "GET_ACCOUNT_LIST";
export const GET_ACCOUNT_LIST_SUCCESS = "GET_ACCOUNT_LIST_SUCCESS";
export const GET_ACCOUNT_LIST_FAILED = "GET_ACCOUNT_LIST_FAILED";

export const ADD_NEW_ACCOUNT = "ADD_NEW_ACCOUNT";
export const ADD_NEW_ACCOUNT_SUCCESS = "ADD_NEW_ACCOUNT_SUCCESS";
export const ADD_NEW_ACCOUNT_FAILED = "ADD_NEW_ACCOUNT_FAILED";

export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";

export const SIGNIN_FAILED = "SIGNIN_FAILED";

export const LOG_OUT = "LOG_OUT";
