export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const ADD_AMOUNT_OF_PRODUCT = "ADD_AMOUNT_OF_PRODUCT";
export const ADD_AMOUNT_OF_PRODUCT_SUCCESS = "ADD_AMOUNT_OF_PRODUCT_SUCCESS";
export const ADD_AMOUNT_OF_PRODUCT_FAILED = "ADD_AMOUNT_OF_PRODUCT_FAILED";

export const MINUS_AMOUNT_OF_PRODUCT = "MINUS_AMOUNT_OF_PRODUCT";
export const MINUS_AMOUNT_OF_PRODUCT_SUCCESS =
  "MINUS_AMOUNT_OF_PRODUCT_SUCCESS";
export const MINUS_AMOUNT_OF_PRODUCT_FAILED = "MINUS_AMOUNT_OF_PRODUCT_FAILED";

export const GET_CART_LIST = "GET_CART_LIST";
export const GET_CART_LIST_SUCCESS = "GET_CART_LIST_SUCCESS";
export const GET_CART_LIST_FAILED = "GET_CART_LIST_FAILED";

export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const DELETE_PRODUCT_FROM_CART_SUCCESS =
  "DELETE_PRODUCT_FROM_CART_SUCCESS";
export const DELETE_PRODUCT_FROM_CART_FAILED =
  "DELETE_PRODUCT_FROM_CART_FAILED";

export const CLEAR_CART = "CLEAR_CART";
