export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";

export const FILTER_LIST = "FILTER_LIST";
export const FILTER_LIST_SUCCESS = "FILTER_LIST_SUCCESS";
export const FILTER_LIST_FAILED = "FILTER_LIST_FAILED";
