export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SHOW_CONFIRM_NOFICATION = "SHOW_CONFIRM_NOFICATION";
export const HIDE_CONFIRM_NOFICATION = "HIDE_CONFIRM_NOFICATION";

export const SHOW_LOGIN_NOFICATION = "SHOW_LOGIN_NOFICATION";
export const HIDE_LOGIN_NOFICATION = "HIDE_LOGIN_NOFICATION";
