export const GET_WISHLIST = "GET_WISHLIST_";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST__SUCCESS";
export const GET_WISHLIST_FAILED = "GET_WISHLIST__FAILED";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAILED = "ADD_TO_WISHLIST_FAILED";

export const DELETE_FROM_WISHLIST = "DELETE_FROM_WISHLIST";
export const DELETE_FROM_WISHLIST_SUCCESS = "DELETE_FROM_WISHLIST_SUCCESS";
export const DELETE_FROM_WISHLIST_FAILED = "DELETE_FROM_WISHLIST_FAILED";
